name: "Auto Approve"
description: "Automatically approve pull requests"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  github-token-one:
    description: "The GITHUB_TOKEN secret for the first auto-approval"
    required: true
  github-token-two:
    description: "The GITHUB_TOKEN secret for the second auto-approval"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
